### ISSUE TITLE
Creating Header Component

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/dating-app-mern#6]
### Create a header component

**tasks**
- [ ] Install Material UI

- [ ] Create a components folder inside the src folder

- [ ] Create two files : header.component.jsx and header.styles.css
